version: '3'

services:
  back:
    build: docker/Node/back
    container_name: back
    tty: true
    volumes:
    - ./backend:/var/www
    ports:
    - 8000:8080
    depends_on:
      - db
  front:
    build: docker/Node/front
    container_name: front
    tty: true
    volumes:
    - ./frontend:/var/www
    ports:
    - 80:8080
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
       - 3306:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root